[server]
headless = true
port = 80
[browser]
serverAddress = “www.turtleshell.io”
[theme]
primaryColor="#82E0AA"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#ECF0F1"
textColor="#17202A"
font="sans serif"